import { Icon } from "@/models/Icons/Icon.model";

const icons: Icon[] = [
  { name: "login", css: ["e92f", "e93a"], version: "2.12" },
  { name: "logout", css: ["e93b", "e93c"], version: "2.12" },
  { name: "question-triangle", css: ["e93d"], version: "2.12" },
  { name: "chevron-down", css: ["e94a"], version: "2.12" },
  { name: "chevron-left", css: ["e94d"], version: "2.12" },
  { name: "chevron-up", css: ["e95f"], version: "2.12" },
  { name: "double-chevron-down", css: ["e968"], version: "2.12" },
  { name: "double-chevron-left", css: ["e969"], version: "2.12" },
  { name: "double-chevron-right", css: ["e96a"], version: "2.12" },
  { name: "double-chevron-up", css: ["e96b"], version: "2.12" },
  { name: "exclamation-circle", css: ["e97b"], version: "2.12" },
  { name: "exclamation-triangle", css: ["e97f"], version: "2.12" },
  { name: "question-circle", css: ["e986"], version: "2.12" },
  { name: "arrow-return", css: ["e9d0"], version: "2.12" },
  { name: "calculator", css: ["e9d1"], version: "2.12" },
  { name: "chevron-right", css: ["e9d2"], version: "2.12" },
  { name: "cocktail", css: ["e9d3"], version: "2.12" },
  { name: "color-fan", css: ["e9da"], version: "2.12" },
  { name: "fast-backward", css: ["e9db"], version: "2.12" },
  { name: "filter", css: ["e9dc"], version: "2.12" },
  { name: "flashlight", css: ["e9dd", "e9f4"], version: "2.12" },
  { name: "numpad", css: ["e9f5"], version: "2.12" },
  { name: "star", css: ["e9f6"], version: "2.12" },
  { name: "arrow-down", css: ["e9f7"], version: "2.12" },
  { name: "arrow-left", css: ["e9f8"], version: "2.12" },
  { name: "arrow-right", css: ["e9f9"], version: "2.12" },
  { name: "arrow-up", css: ["e9fa"], version: "2.12" },
  { name: "fast-forward", css: ["e9fb"], version: "2.12" },
  { name: "list-add", css: ["e9fc", "e9fd"], version: "2.12" },
  { name: "pause", css: ["e9fe"], version: "2.12" },
  { name: "play", css: ["e9ff"], version: "2.12" },
  { name: "step-backwards", css: ["ea00"], version: "2.12" },
  { name: "step-forward", css: ["ea01"], version: "2.12" },
  { name: "stop", css: ["ea02"], version: "2.12" },
  { name: "wifi-0", css: ["ea03", "ea04"], version: "2.12" },

  { name: "chart-stocks", css: ["e9eb", "e9ec"], version: "2.11" },
  { name: "clock-simple", css: ["e9ed", "e9ee"], version: "2.11" },
  { name: "credit-card", css: ["e9ef", "e9f0"], version: "2.11" },
  { name: "dollar", css: ["e9f1"], version: "2.11" },
  { name: "globe", css: ["e9f2"], version: "2.11" },
  { name: "vehicle-front", css: ["e9f3"], version: "2.11" },

  { name: "pin-person", css: ["e9d9"], version: "2.10" },
  { name: "band-aid", css: ["e9c2"], version: "2.10" },
  { name: "female", css: ["e9c3"], version: "2.10" },
  { name: "headphone", css: ["e9c4", "e9c5"], version: "2.10" },
  { name: "headset", css: ["e9c6", "e9c7"], version: "2.10" },
  { name: "heartbeat", css: ["e9c8"], version: "2.10" },
  { name: "heart-broken", css: ["e9c9"], version: "2.10" },
  { name: "pin", css: ["e9ca"], version: "2.10" },
  { name: "apple", css: ["e9cb"], version: "2.10" },
  { name: "exchange", css: ["e9cc", "e9cd"], version: "2.10" },
  { name: "exclamation", css: ["e9ce", "e9cf"], version: "2.10" },
  { name: "exclamation-circle", css: ["e9d0", "e9d1"], version: "2.10" },
  { name: "exclamation-triangle", css: ["e9d2", "e9d3"], version: "2.10" },
  { name: "heart-empty", css: ["e9d4"], version: "2.10" },
  { name: "male", css: ["e9d5"], version: "2.10" },
  { name: "microphone", css: ["e9d6", "e9d7"], version: "2.10" },
  { name: "minecraft", css: ["e9d8"], version: "2.10" },
  { name: "question-circle", css: ["e9da", "e9db"], version: "2.10" },
  { name: "question-triangle", css: ["e9dc", "e9dd"], version: "2.10" },
  { name: "tesla", css: ["e9de"], version: "2.10" },
  { name: "thermometer-three-quarter", css: ["e9df", "e9e0"], version: "2.10" },
  { name: "barometer", css: ["e9e1", "e9e2"], version: "2.10" },
  { name: "thermometer-empty", css: ["e9e3", "e9e4"], version: "2.10" },
  { name: "thermometer-full", css: ["e9e5", "e9e6"], version: "2.10" },
  { name: "thermometer-half", css: ["e9e7", "e9e8"], version: "2.10" },
  { name: "thermometer-quarter", css: ["e9e9", "e9ea"], version: "2.10" },

  { name: "key", css: ["e9b3", "e9b4"], version: "2.9" },
  { name: "lock-closed", css: ["e9b5", "e9b6"], version: "2.9" },
  { name: "lock-opened", css: ["e9b7", "e9b8"], version: "2.9" },
  { name: "alarm", css: ["e9b9", "e9ba"], version: "2.9" },
  { name: "minus", css: ["e9bb"], version: "2.9" },
  { name: "plus", css: ["e9bc"], version: "2.9" },
  { name: "segment", css: ["e9bd", "e9be"], version: "2.9" },
  { name: "slider", css: ["e9bf", "e9c0"], version: "2.9" },
  { name: "tooltip", css: ["e9c1"], version: "2.9" },

  { name: "dice-4", css: ["e98e", "e98f"], version: "2.8" },
  { name: "dice-5", css: ["e990", "e991"], version: "2.8" },
  { name: "bar", css: ["e992"], version: "2.8" },
  { name: "bar-progress", css: ["e993", "e994"], version: "2.8" },
  { name: "crosshair", css: ["e995"], version: "2.8" },
  { name: "dice-1", css: ["e996", "e007"], version: "2.8" },
  { name: "dice-2", css: ["e998", "e999"], version: "2.8" },
  { name: "dice-3", css: ["e99a", "e99b"], version: "2.8" },
  { name: "dice-6", css: ["e99c", "e99d"], version: "2.8" },
  { name: "moon", css: ["e99e"], version: "2.8" },
  { name: "peace", css: ["e99f", "e9a0"], version: "2.8" },
  { name: "quote-left", css: ["e9a1", "e9a2"], version: "2.8" },
  { name: "repeat", css: ["e9a3"], version: "2.8" },
  { name: "sun", css: ["e9a4", "e9a5"], version: "2.8" },
  { name: "swap", css: ["e9a6", "e9a7"], version: "2.8" },
  { name: "user-circle", css: ["e9a8", "e9a9"], version: "2.8" },
  { name: "wifi-1", css: ["e9aa", "e9ab"], version: "2.8" },
  { name: "wifi-2", css: ["e9ac", "e9ad"], version: "2.8" },
  { name: "wifi-3", css: ["e9ae"], version: "2.8" },
  { name: "percentage", css: ["e9af", "e9b0"], version: "2.8" },
  { name: "quote-right", css: ["e9b1", "e9b2"], version: "2.8" },

  { name: "camera", css: ["e98c", "e98d"] },
  { name: "chart-donut", css: ["e900", "e901"] },
  { name: "chart-pie", css: ["e902", "e903"] },
  { name: "chart-radial", css: ["e904", "e905"] },
  { name: "computer", css: ["e906", "e907"] },
  { name: "github", css: ["e908"] },
  { name: "hockey-sticks", css: ["e909", "e90a"] },
  { name: "modal", css: ["e90b", "e90c"] },
  { name: "phone", css: ["e90d", "e90e"] },
  { name: "spinner", css: ["e90f"] },
  { name: "tabbar", css: ["e910", "e911"] },
  { name: "toggle", css: ["e912", "e913"] },
  { name: "windows", css: ["e914", "e915"] },
  { name: "amspro", css: ["e916", "e917"] },
  { name: "button", css: ["e918", "e919"] },
  { name: "card", css: ["e91a", "e91b"] },
  { name: "chart-bar", css: ["e91c", "e91d"] },
  { name: "chart-empty", css: ["e91e"] },
  { name: "chart-radar", css: ["e91f"] },
  { name: "checkbox", css: ["e920", "e921"] },
  { name: "code", css: ["e922"] },
  { name: "component", css: ["e923"] },
  { name: "divider", css: ["e924", "e925"] },
  { name: "download", css: ["e926", "e927"] },
  { name: "hockey-stick", css: ["e928"] },
  { name: "input", css: ["e929", "e92a"] },
  { name: "painting", css: ["e92b", "e92c"] },
  { name: "table", css: ["e92d", "e92e"] },
  { name: "arrow-left", css: ["e92f"] },
  { name: "arrow-up-right", css: ["e930"] },
  { name: "book", css: ["e931", "e932"] },
  { name: "book-p", css: ["e933", "e934"] },
  { name: "book-q", css: ["e935", "e936"] },
  { name: "chart-line", css: ["e937", "e938"] },
  { name: "checkmark", css: ["e939"] },
  { name: "double-arrow-down", css: ["e93a"] },
  { name: "double-arrow-left", css: ["e93b"] },
  { name: "double-arrow-right", css: ["e93c"] },
  { name: "double-arrow-up", css: ["e93d"] },
  { name: "scale", css: ["e93e", "e93f"] },
  { name: "sidebar", css: ["e940", "e941"] },
  { name: "todo", css: ["e942"] },
  { name: "user", css: ["e943"] },
  { name: "user-active", css: ["e944", "e945"] },
  { name: "user-inactive", css: ["e946", "e947"] },
  { name: "users", css: ["e948", "e949"] },
  { name: "arrow-down", css: ["e94a"] },
  { name: "arrow-down-left", css: ["e94b"] },
  { name: "arrow-down-right", css: ["e94c"] },
  { name: "arrow-up", css: ["e94d"] },
  { name: "arrow-up-left", css: ["e94e"] },
  { name: "bucket", css: ["e94f", "e950"] },
  { name: "dot", css: ["e951"] },
  { name: "dots", css: ["e952"] },
  { name: "farm", css: ["e953", "e954"] },
  { name: "list", css: ["e955", "e956"] },
  { name: "list-check", css: ["e957", "e958"] },
  { name: "moped-license-plate", css: ["e959"] },
  { name: "offer", css: ["e95a"] },
  { name: "scale-out", css: ["e95d", "e95e"] },
  { name: "scale-in", css: ["e95b", "e95c"] },
  { name: "arrow-right", css: ["e95f"] },
  { name: "at", css: ["e960"] },
  { name: "circle", css: ["e961"] },
  { name: "cross", css: ["e962"] },
  { name: "hashtag", css: ["e963"] },
  { name: "lens", css: ["e964", "e965"] },
  { name: "list-bullet", css: ["e966", "e967"] },
  { name: "pencil", css: ["e96c"] },
  { name: "questionmark", css: ["e96d", "e96e"] },
  { name: "reply", css: ["e96f"] },
  { name: "server", css: ["e970"] },
  { name: "share", css: ["e971", "e972"] },
  { name: "tools", css: ["e973"] },
  { name: "trashcan", css: ["e974", "e975"] },
  { name: "user-card", css: ["e976", "e977"], version: "2.0" },
  { name: "add", css: ["e978", "e979"], version: "2.0" },
  { name: "checkmark-circle", css: ["e97a", "e97b"], version: "2.0" },
  { name: "checkmarks", css: ["e97c", "e97d"], version: "2.0" },
  { name: "cross-circle", css: ["e97e", "e97f"], version: "2.0" },
  { name: "gears", css: ["e980", "e981"], version: "2.0" },
  { name: "heart", css: ["e982"], version: "2.0" },
  { name: "house", css: ["e983", "e984"], version: "2.0" },
  { name: "i-circle", css: ["e985", "e986"], version: "2.0" },
  { name: "save", css: ["e987", "e988"], version: "2.0" },
  { name: "stars", css: ["e989", "e98a"], version: "2.0" },
  { name: "thunder", css: ["e98b"], version: "2.0" }
];

export default icons;
