import { Icon } from "@/models/Icons/Icon.model";

const icons: Icon[] = [
  { name: "pin-person", css: "e9d9", version: "2.10" },
  { name: "band-aid", css: "e9c2", version: "2.10" },
  { name: "female", css: "e9c3", version: "2.10" },
  { name: "headphone", css: "e9c4", version: "2.10" },
  { name: "headset", css: "e9c6", version: "2.10" },
  { name: "heartbeat", css: "e9c8", version: "2.10" },
  { name: "heart-broken", css: "e9c9", version: "2.10" },
  { name: "pin", css: "e9ca", version: "2.10" },
  { name: "apple", css: "e9cb", version: "2.10" },
  { name: "exchange", css: "e9cc", version: "2.10" },
  { name: "exclamation", css: "e9ce", version: "2.10" },
  { name: "exclamation-circle", css: "e9d0", version: "2.10" },
  { name: "exclamation-triangle", css: "e9d2", version: "2.10" },
  { name: "heart-empty", css: "e9d4", version: "2.10" },
  { name: "male", css: "e9d5", version: "2.10" },
  { name: "microphone", css: "e9d6", version: "2.10" },
  { name: "minecraft", css: "e9d8", version: "2.10" },
  { name: "question-circle", css: "e9da", version: "2.10" },
  { name: "question-triangle", css: "e9dc", version: "2.10" },
  { name: "tesla", css: "e9de", version: "2.10" },
  { name: "thermometer-three-quarter", css: "e9df", version: "2.10" },
  { name: "barometer", css: "e9e1", version: "2.10" },
  { name: "thermometer-empty", css: "e9e3", version: "2.10" },
  { name: "thermometer-full", css: "e9e5", version: "2.10" },
  { name: "thermometer-half", css: "e9e7", version: "2.10" },
  { name: "thermometer-quarter", css: "e9e9", version: "2.10" },

  { name: "key", css: "e9b3", version: "2.9" },
  { name: "lock-closed", css: "e9b5", version: "2.9" },
  { name: "lock-opened", css: "e9b7", version: "2.9" },
  { name: "alarm", css: "e9b9", version: "2.9" },
  { name: "minus", css: "e9bb", version: "2.9" },
  { name: "plus", css: "e9bc", version: "2.9" },
  { name: "segment", css: "e9bd", version: "2.9" },
  { name: "slider", css: "e9bf", version: "2.9" },
  { name: "tooltip", css: "e9c1", version: "2.9" },
  { name: "dice-4", css: "e98e", version: "2.8" },
  { name: "dice-5", css: "e990", version: "2.8" },
  { name: "bar", css: "e992", version: "2.8" },
  { name: "bar-progress", css: "e993", version: "2.8" },
  { name: "crosshair", css: "e995", version: "2.8" },
  { name: "dice-1", css: "e996", version: "2.8" },
  { name: "dice-2", css: "e998", version: "2.8" },
  { name: "dice-3", css: "e99a", version: "2.8" },
  { name: "dice-6", css: "e99c", version: "2.8" },
  { name: "moon", css: "e99e", version: "2.8" },
  { name: "peace", css: "e99f", version: "2.8" },
  { name: "quote-left", css: "e9a1", version: "2.8" },
  { name: "repeat", css: "e9a3", version: "2.8" },
  { name: "sun", css: "e9a4", version: "2.8" },
  { name: "swap", css: "e9a6", version: "2.8" },
  { name: "user-circle", css: "e9a8", version: "2.8" },
  { name: "wifi-1", css: "e9aa", version: "2.8" },
  { name: "wifi-2", css: "e9ac", version: "2.8" },
  { name: "wifi-3", css: "e9ae", version: "2.8" },
  { name: "percentage", css: "e9af", version: "2.8" },
  { name: "quote-right", css: "e9b1", version: "2.8" },
  { name: "camera", css: "e98c" },
  { name: "chart-donut", css: "e900" },
  { name: "chart-pie", css: "e902" },
  { name: "chart-radial", css: "e904" },
  { name: "computer", css: "e906" },
  { name: "github", css: "e908" },
  { name: "hockey-sticks", css: "e909" },
  { name: "modal", css: "e90b" },
  { name: "phone", css: "e90d" },
  { name: "spinner", css: "e90f" },
  { name: "tabbar", css: "e910" },
  { name: "toggle", css: "e912" },
  { name: "windows", css: "e914" },
  { name: "amspro", css: "e916" },
  { name: "button", css: "e918" },
  { name: "card", css: "e91a" },
  { name: "chart-bar", css: "e91c" },
  { name: "chart-empty", css: "e91e" },
  { name: "chart-radar", css: "e91f" },
  { name: "checkbox", css: "e920" },
  { name: "code", css: "e922" },
  { name: "component", css: "e923" },
  { name: "divider", css: "e924" },
  { name: "download", css: "e926" },
  { name: "hockey-stick", css: "e928" },
  { name: "input", css: "e929" },
  { name: "painting", css: "e92b" },
  { name: "table", css: "e92d" },
  { name: "arrow-left", css: "e92f" },
  { name: "arrow-up-right", css: "e930" },
  { name: "book", css: "e931" },
  { name: "book-p", css: "e933" },
  { name: "book-q", css: "e935" },
  { name: "chart-line", css: "e937" },
  { name: "checkmark", css: "e939" },
  { name: "double-arrow-down", css: "e93a" },
  { name: "double-arrow-left", css: "e93b" },
  { name: "double-arrow-right", css: "e93c" },
  { name: "double-arrow-up", css: "e93d" },
  { name: "scale", css: "e93e" },
  { name: "sidebar", css: "e940" },
  { name: "todo", css: "e942" },
  { name: "user", css: "e943" },
  { name: "user-active", css: "e944" },
  { name: "user-inactive", css: "e946" },
  { name: "users", css: "e948" },
  { name: "arrow-down", css: "e94a" },
  { name: "arrow-down-left", css: "e94b" },
  { name: "arrow-down-right", css: "e94c" },
  { name: "arrow-up", css: "e94d" },
  { name: "arrow-up-left", css: "e94e" },
  { name: "bucket", css: "e94f" },
  { name: "dot", css: "e951" },
  { name: "dots", css: "e952" },
  { name: "farm", css: "e953" },
  { name: "list", css: "e955" },
  { name: "list-check", css: "e957" },
  { name: "moped-license-plate", css: "e959" },
  { name: "offer", css: "e95a" },
  { name: "scale-out", css: "e95d" },
  { name: "arrow-right", css: "e95f" },
  { name: "at", css: "e960" },
  { name: "circle", css: "e961" },
  { name: "cross", css: "e962" },
  { name: "hashtag", css: "e963" },
  { name: "lens", css: "e964" },
  { name: "list-bullet", css: "e966" },
  { name: "login", css: "e968" },
  { name: "logout", css: "e96a" },
  { name: "pencil", css: "e96c" },
  { name: "questionmark", css: "e96d" },
  { name: "reply", css: "e96f" },
  { name: "server", css: "e970" },
  { name: "share", css: "e971" },
  { name: "tools", css: "e973" },
  { name: "trashcan", css: "e974" },
  { name: "user-card", css: "e976", version: "2.0" },
  { name: "add", css: "e978", version: "2.0" },
  { name: "checkmark-circle", css: "e97a", version: "2.0" },
  { name: "checkmarks", css: "e97c", version: "2.0" },
  { name: "cross-circle", css: "e97e", version: "2.0" },
  { name: "gears", css: "e980", version: "2.0" },
  { name: "heart", css: "e982", version: "2.0" },
  { name: "house", css: "e983", version: "2.0" },
  { name: "i-circle", css: "e985", version: "2.0" },
  { name: "save", css: "e987", version: "2.0" },
  { name: "stars", css: "e989", version: "2.0" },
  { name: "thunder", css: "e98b", version: "2.0" }
];

export default icons;
