import routes from '@/constants/routes';
import { Project } from '@/models';
import tools from './tools';

const projects: Project[] = [
  {
    routeName: routes.tccomponents,
    title: 'TC Components',
    description:
      'A library of high-quality ready to use components that will help you speed up your development workflow.',
    type: 'Vue Component Library',
    icon: 'tccomponents',
    assets: {
      hero: 'assets/projects/tccomponents/hero.png',
      thumbnail: 'assets/projects/tccomponents/thumbnail.png',
    },
    showOnHome: true,
    website: 'https://components.timos.design',
    github: 'https://github.com/TimoScheuermann/Timos-Components',
    tools: [
      tools.adobexd,
      tools.css3,
      tools.html5,
      tools.vuejs,
      tools.npm,
      tools.git,
      tools.typescript,
      tools.javascript,
      tools.nodejs,
      tools.yarn,
    ],
  },
  {
    routeName: routes.timosicons,
    title: "Timo's Icons",
    description:
      'With loved designed, highly professional, minimalistic icons for your next project.',
    type: 'Icon Library',
    icon: 'timos-icons',
    assets: {
      hero: 'assets/projects/timosicons/hero.png',
      thumbnail: 'assets/projects/timosicons/thumbnail.png',
    },
    showOnHome: true,
    website: 'https://icons.timos.design',
    github: 'https://github.com/TimoScheuermann/Timos-Icons',
    tools: [
      tools.adobexd,
      tools.css3,
      tools.html5,
      tools.vuejs,
      tools.git,
      tools.typescript,
      tools.nodejs,
      tools.yarn,
      tools.icomoon,
    ],
  },
  {
    routeName: routes.timosaccounts,
    title: "Timo's Accounts",
    description:
      'A single account grands you access to every feature on timos.design. From writing comments to news, suggesting changes to tccomponents or requesting new icons',
    type: 'Website',
    icon: 'timos-accounts',
    assets: {
      hero: 'assets/projects/timosaccounts/hero.png',
      thumbnail: 'assets/projects/timosaccounts/thumbnail.png',
    },
    showOnHome: true,
    brightThumbnail: true,
    website: 'https://accounts.timos.design',
    github: 'https://github.com/TimoScheuermann/Timos-Accounts',
    tools: [
      tools.nestjs,
      tools.css3,
      tools.git,
      tools.mongodb,
      tools.html5,
      tools.yarn,
      tools.vuejs,
      tools.typescript,
      tools.adobexd,
      tools.npm,
    ],
  },
  {
    routeName: routes.gastroassistant,
    title: 'Gastro Assistant',
    description: 'soon.',
    type: 'Website',
    icon: 'gastro-assistant',
    assets: {
      hero: 'assets/projects/gastroassistant/hero.png',
      thumbnail: 'assets/projects/gastroassistant/thumbnail.png',
    },
    website: 'https://gaestro.org',
    tools: [
      tools.nestjs,
      tools.css3,
      tools.git,
      tools.html5,
      tools.yarn,
      tools.npm,
      tools.vuejs,
      tools.typescript,
      tools.adobexd,
    ],
  },
  {
    routeName: routes.websitebuilder,
    title: 'Website Builder',
    description: 'soon.',
    type: 'Website',
    icon: 'component',
    assets: {
      hero: 'assets/projects/websitebuilder/hero.svg',
      thumbnail: 'assets/projects/websitebuilder/thumbnail.png',
    },
    brightThumbnail: true,
    website: 'https://websitebuilder.timos.design',
    github: 'https://github.com/TimoScheuermann/Timos-Websitebuilder',
    tools: [
      tools.css3,
      tools.git,
      tools.mongodb,
      tools.html5,
      tools.yarn,
      tools.vuejs,
      tools.typescript,
      tools.adobexd,
      tools.nestjs,
    ],
  },
  {
    routeName: routes.investingcollectors,
    title: 'Investing Collectors',
    description:
      'At Investing Collectors we are firm believers in the innovative power of car values, cryptocurrencies, digitised assets and blockchain technology. Our mission is to tear down the barriers to personal finance and bring emotional binding rare cars into the 21st century.',
    type: 'Website',
    icon: 'vehicle-front',
    assets: {
      hero: 'assets/projects/investingcollectors/hero.png',
      thumbnail: 'assets/projects/investingcollectors/thumbnail.png',
    },
    brightThumbnail: true,
    website: 'https://wip-investing-collectors.netlify.app',
    tools: [
      tools.adobexd,
      tools.css3,
      tools.html5,
      tools.git,
      tools.typescript,
      tools.nodejs,
      tools.yarn,
      tools.affinityphoto,
      tools.nuxtjs,
    ],
  },
  {
    routeName: routes.workgallery,
    title: 'Work Gallery',
    description:
      'Just some random screenshots, design ideas that I came across over the years.',
    type: 'Workgallery',
    icon: 'photos',
    assets: {
      hero: 'assets/projects/workgallery/hero.png',
      thumbnail: 'assets/projects/workgallery/thumbnail.png',
    },
  },
  {
    routeName: routes.dhbwrichie,
    title: 'DHBW Richie',
    description:
      'Fun little school project. Ask Richie specific questions to a lesson.',
    type: 'University Project',
    icon: 'lens',
    assets: {
      hero: 'assets/projects/dhbwrichie/hero.png',
      thumbnail: 'assets/projects/dhbwrichie/thumbnail.png',
    },
    website: 'https://dhbw-richie.netlify.app',
    github: 'https://github.com/TimoScheuermann/DHBW-Richie-Redesign',
    tools: [
      tools.adobexd,
      tools.css3,
      tools.html5,
      tools.angular,
      tools.git,
      tools.typescript,
      tools.nodejs,
      tools.yarn,
      tools.mongodb,
      tools.nestjs,
    ],
  },
  {
    routeName: routes.nhlstats,
    title: 'NHL Stats',
    description:
      'Fun little scrool project to get every kind of combination of statistics about NHL Season 18/19',
    type: 'University Project',
    icon: 'hockey-stick',
    assets: {
      hero: 'assets/projects/nhlstats/hero.png',
      thumbnail: 'assets/projects/nhlstats/thumbnail.png',
    },
    github: 'https://github.com/TimoScheuermann/Advanced-DB-Cassandra',
    tools: [
      tools.css3,
      tools.html5,
      tools.vuejs,
      tools.git,
      tools.javascript,
      tools.nodejs,
      tools.npm,
      tools.nestjs,
      tools.cassandra,
    ],
  },
  {
    routeName: routes.amspro,
    title: 'AMS Pro',
    description:
      'Arbeitsschutzsoftware, die sich lohnt. Weil im Bereich Arbeitssicherheit viel schiefgehen kann, bieten wir die optimale Unterstützung. Profitieren Sie von maßgeschneiderter Arbeitssicherheitssoftware, die Sie in jeder Lage unterstützt! Produktdetails.',
    type: 'Icons',
    icon: 'amspro',
    assets: {
      hero: 'assets/projects/amspro/hero.png',
      thumbnail: 'assets/projects/amspro/thumbnail.png',
    },
    showOnHome: true,
    website: 'https://ams-pro.de',
    tools: [tools.adobexd, tools.css3, tools.icomoon, tools.html5],
  },
  {
    routeName: routes.timostranslator,
    title: "Timo's Translator",
    description: 'soon.',
    type: 'Mobile App (PWA)',
    icon: 'timos-translator',
    assets: {
      hero: 'assets/projects/timostranslator/hero.png',
      thumbnail: 'assets/projects/timostranslator/thumbnail.png',
    },
    website: 'https://translator.timos.design',
    github: 'https://github.com/TimoScheuermann/Timos-Translator',
    tools: [
      tools.css3,
      tools.git,
      tools.mongodb,
      tools.html5,
      tools.yarn,
      tools.vuejs,
      tools.typescript,
      tools.adobexd,
      tools.nestjs,
    ],
  },
  {
    routeName: routes.newsroom,
    hideInSidebar: true,
    title: "Timo's Newsroom",
    description:
      "Timo's Newsroom is the source for news about all of my projects. Read annoucements, get updates and learn new features.",
    type: 'Website',
    icon: 'newspaper',
    assets: {
      hero: '',
      thumbnail: 'assets/projects/timosnewsroom/thumbnail.png',
    },
    website: 'https://newsroom.timos.design',
    github: 'https://github.com/TimoScheuermann/Timos-Newsroom',
    tools: [
      tools.css3,
      tools.git,
      tools.mongodb,
      tools.html5,
      tools.yarn,
      tools.vuejs,
      tools.typescript,
      tools.adobexd,
      tools.nestjs,
    ],
  },
];

export default projects;
