export default {
  home: 'home',
  projects: 'projects',
  github: 'github',
  contact: 'contact',
  repertoire: 'repertoire',
  resume: 'resume',
  portfolio: 'home',
  nhlstats: 'nhlstats',
  workgallery: 'workgallery',
  dhbwrichie: 'dhbwrichie',
  timosicons: 'timosicons',
  tccomponents: 'tccomponents',
  amspro: 'amspro',
  investingcollectors: 'investingcollectors',
  notfound: 'notfound',
  privacy: 'privacy',
  termsofuse: 'termsofuse',
  newsroom: 'newsroom',
  timosaccounts: 'timosaccounts',
  cookies: 'cookies',
  impressum: 'impressum',
};
